# Host to use for canonical URL generation (without trailing slash)
host: .

# Header-related options
show_govuk_logo: true
service_name: csvwlib
service_link: https://www.github.com/GSS-Cogs/csvwlib
phase: Alpha

# Links to show on right-hand-side of header
header_links:
  Documentation: ./index.html

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: true

# Enable multipage navigation in the sidebar
multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Table of contents depth â€“ how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 6

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

show_contribution_banner: true
github_repo: GSS-Cogs/csvwlib
