site_name: csvcubed
site_url: https://gss-cogs.github.io/csvcubed-docs/external
nav:
  - Home:
      - index.md
  - Quick start: 
      - quick-start/index.md
      - Installation: quick-start/installation.md
      - Designing a CSV: quick-start/designing-csv.md
      - Building a CSV-W: quick-start/build.md
      - Describing your CSV: quick-start/describing-csv.md
      - Linking data: quick-start/linking-data.md
      - Inspecting a CSV-W: quick-start/inspect.md
  - Guides:
      - guides/index.md
      - Commands: 
        - build: guides/command-line/build-command.md
        - inspect: guides/command-line/inspect-command.md
        - Logging: guides/command-line/logging.md
      - Configuration:
        - guides/configuration/index.md
        - By convention: guides/configuration/convention.md
        - qube-config.json: guides/configuration/qube-config.md
        - Templates: guides/configuration/templates.md
        - Units: guides/configuration/units.md
      - Errors:
        - guides/errors/index.md 
        - build command errors: guides/errors/build-command-errors/index.md
        - inspect command errors: guides/errors/inspect-command-errors/index.md
      - Handling missing observed values: guides/missing-observed-values.md
      - Linked Data:
        - Units: guides/linked-data/units.md
        - Organisations: guides/linked-data/organisations.md
      - Raise an issue: guides/raise-issue.md
      - Shape your data: guides/shape-data.md
      - Working with URIs: guides/uris.md
  - Glossary:
      - glossary/index.md
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - search.highlight
    - navigation.instant
    # - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.integrate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true 
plugins:
  - search
  - mermaid2