site_name: csvcubed
site_url: https://gss-cogs.github.io/csvcubed-docs/external
repo_url: https://github.com/GSS-Cogs/csvcubed
repo_name: GSS-Cogs/csvcubed
nav:
  - Home:
      - index.md
  - Quick start:
      - quick-start/index.md
      - Installation: quick-start/installation.md
      - Designing a CSV: quick-start/designing-csv.md
      - Building a CSV-W: quick-start/build.md
      - Describing your CSV: quick-start/describing-csv.md
      - Linking data: quick-start/linking-data.md
      - Inspecting a CSV-W: quick-start/inspect.md
  - Guides:
      - guides/index.md
      - Commands:
        - build: guides/command-line/build-command.md
        - code list build: guides/command-line/code-list-build-command.md
        - inspect: guides/command-line/inspect-command.md
        - Logging: guides/command-line/logging.md
      - Configuration:
        - guides/configuration/index.md
        - By convention: guides/configuration/convention.md
        - Explicit configuration:
          - guides/configuration/qube-config/index.md
          - Catalog metadata: guides/configuration/qube-config/metadata.md
          - Column definitions:
            - guides/configuration/qube-config/columns/index.md
            - Dimension columns: guides/configuration/qube-config/columns/dimensions.md
            - Observations columns: guides/configuration/qube-config/columns/observations.md
            - Measures columns: guides/configuration/qube-config/columns/measures.md
            - Units columns: guides/configuration/qube-config/columns/units.md
            - Attribute columns:
              - guides/configuration/qube-config/columns/attributes/index.md
              - Resource attributes: guides/configuration/qube-config/columns/attributes/attribute-resources.md
              - Literal attributes: guides/configuration/qube-config/columns/attributes/attribute-literals.md
              - Attribute values: guides/configuration/qube-config/columns/attributes/attribute-values.md
          - Using templates: guides/configuration/qube-config/templates.md
          - Measure definitions: guides/configuration/qube-config/measure-definitions.md
          - Unit definitions: guides/configuration/qube-config/unit-definitions.md
          - Code Lists: guides/configuration/qube-config/code-list-config.md
      - Shape your data:
        - guides/shape-data/index.md
        - Standard shape: guides/shape-data/standard-shape.md
        - Pivoted shape: guides/shape-data/pivoted-shape.md
        - Shape conversion: guides/shape-data/shape-conversion.md
      - Handling missing observed values: guides/missing-observed-values.md
      - Errors:
        - guides/errors/index.md
        - build command errors: guides/errors/build-command-errors/index.md
        - inspect command errors: guides/errors/inspect-command-errors/index.md
      - Linked Data:
        - Licenses: guides/linked-data/licenses.md
        - Organisations: guides/linked-data/organisations.md
        - Units: guides/linked-data/units.md
      - Raise an issue: guides/raise-issue.md
      - Working with URIs: guides/uris.md
      - Build with GitHub: guides/csv-to-csvw-github-action.md
  - Glossary:
      - glossary/index.md
theme:
  name: material
  features:
    - search.highlight
    - navigation.instant
    # - navigation.expand
#    - toc.integrate
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tracking
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - mermaid2
