name: Test csvcubed on main branch push
on:
  push:
    branches:
      - main

jobs:
  test_in_environments:
    strategy:
      matrix:
        # Test on Windows + Ubuntu on oldest + newest supported versions of python.
        python-version: ['3.9', '3.11']
        os: [ubuntu-latest, windows-latest]
    uses: ./.github/workflows/reusable-test.yaml
    secrets: 
      ACCESS_REPOS_GH: ${{ secrets.ACCESS_REPOS_GH }}
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
  
  build_package_and_documentation:
    if: needs.test_in_environments.result == 'success'
    needs: [test_in_environments]
    uses: ./.github/workflows/reusable-build.yaml

  publish_package_and_documentation:
    if: needs.build_package_and_documentation.result == 'success'
    needs: [build_package_and_documentation]
    uses: ./.github/workflows/reusable-deploy.yaml
    secrets: inherit